/** SATRIA BUILDER v1.0.0 - direct SpreadsheetApp, Execute as ME, Anyone */
const APP = Object.freeze({name:'SATRIA Builder', version:'1.0.0', tokenTtl:21600, masterProp:'MASTER_SPREADSHEET_ID', bootProp:'BOOTSTRAPPED'});
const ROLES = ['owner','guru','karyawan','admin_kelas','siswa'];
const MASTER = {
  MASTER_USERS:['id_user','username','password_sha','nama','email','role','id_ref','nip_nisn','id_kelas','spreadsheet_id','status','created_at','updated_at'],
  MASTER_GURU:['id_guru','nip','nama','email','status'],
  MASTER_KARYAWAN:['id_karyawan','nip','nama','email','status'],
  MASTER_KELAS:['id_kelas','kode_kelas','nama_kelas','spreadsheet_id','admin_username','status','created_at','updated_at'],
  MASTER_MAPEL:['id_mapel','kode_mapel','nama_mapel','kelompok','status'],
  MASTER_MENU:['id_menu','nama_menu','judul','icon','sort_order','roles','module_id','sheet_name','description','status','created_at','updated_at'],
  MASTER_MODUL:['id_modul','kode_modul','nama_kegiatan','description','sheet_name','headers_json','roles','status','created_at','updated_at'],
  MASTER_PERMISSION:['id_permission','role','menu_id','can_view','can_add','can_edit','can_delete','updated_at']
};
const SEED_MODULES = [
  ['MODUL-7KAIH','7KAIH','MODUL 7KAIH','Kegiatan pembiasaan dan penguatan karakter 7KAIH.','TRX_7KAIH',['tanggal','siswa_id','nama_siswa','kelas','indikator','uraian_kegiatan','catatan','bukti_fisik','created_at'],['siswa','admin_kelas','guru']],
  ['MODUL-BELAJAR','BELAJAR_MANDIRI','MODUL BELAJAR MANDIRI','Kegiatan belajar mandiri siswa per kelas.','TRX_BELAJAR_MANDIRI',['tanggal','siswa_id','nama_siswa','kelas','mata_pelajaran','materi','aktivitas','hasil_belajar','refleksi','bukti_fisik','created_at'],['siswa','admin_kelas','guru']],
  ['MODUL-LITERASI','LITERASI','MODUL KEGIATAN LITERASI','Pencatatan kegiatan literasi siswa.','TRX_LITERASI',['tanggal','siswa_id','nama_siswa','kelas','jenis_literasi','judul_bacaan','ringkasan','refleksi','bukti_fisik','created_at'],['siswa','admin_kelas','guru']]
];
function doGet(){return HtmlService.createHtmlOutputFromFile('index').setTitle(APP.name).setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);}
function bootstrapOwner(p){if(isBootstrapped_())throw new Error('Sistem sudah di-bootstrap.');p=p||{};const id=String(p.masterSpreadsheetId||'').trim(),u=norm_(p.username),pw=String(p.password||'');if(!id||!u||pw.length<4)throw new Error('MASTER ID, username, password minimal 4 karakter wajib.');const ss=SpreadsheetApp.openById(id);ensureMaster_(ss);const sh=ss.getSheetByName('MASTER_USERS');if(read_(sh).rows.some(r=>norm_(r[1])===u))throw new Error('Username owner sudah ada.');const now=new Date();append_(sh,MASTER.MASTER_USERS,{id_user:'USR-OWNER',username:u,password_sha:sha_(pw),nama:String(p.nama||'Owner'),role:'owner',status:'ACTIVE',created_at:now,updated_at:now});seedModules_(ss);PropertiesService.getScriptProperties().setProperties({MASTER_SPREADSHEET_ID:id,BOOTSTRAPPED:'1'});return{ok:true};}
function login(username,password){if(!isBootstrapped_())return{ok:false,needsBootstrap:true};ensureMasterUsersSchema_();const u=norm_(username),pw=String(password||''),masterUsers=read_(master_().getSheetByName('MASTER_USERS')).rows;let found=masterUsers.find(x=>norm_(x[1])===u&&String(x[2])===sha_(pw)&&String(x[10]).toUpperCase()!=='INACTIVE');let user;if(found){const role=norm_(found[5]);if(!ROLES.includes(role))throw new Error('Role tidak valid.');user={id_user:found[0],username:u,nama:found[3],email:found[4]||'',role,id_ref:found[6]||'',nip_nisn:found[7]||'',id_kelas:found[8]||'',spreadsheet_id:found[9]||''};}else{const classes=read_(master_().getSheetByName('MASTER_KELAS')).rows;for(const cr of classes){const c=obj_(MASTER.MASTER_KELAS,cr);if(!c.spreadsheet_id)continue;try{const sh=SpreadsheetApp.openById(c.spreadsheet_id).getSheetByName('SISWA');if(!sh)continue;const r=read_(sh).rows.find(x=>norm_(x[1])===u&&String(x[2])===sha_(pw)&&String(x[6]).toUpperCase()!=='INACTIVE');if(r){user={id_user:r[0],username:u,nama:r[4],role:'siswa',id_kelas:c.id_kelas};break;}}catch(e){}}}if(!user)throw new Error('Username atau password salah.');const token=Utilities.getUuid()+'-'+Utilities.getUuid();CacheService.getScriptCache().put('AUTH:'+token,JSON.stringify(user),APP.tokenTtl);return{ok:true,token,user,menus:menus_(user)};}
function logout(token){if(token)CacheService.getScriptCache().remove('AUTH:'+token);return{ok:true};}
function session(token){const s=auth_(token);return{user:s,menus:menus_(s)};}
function api(token,action,p){const s=auth_(token);p=p||{};switch(action){case'dashboard':return dashboard_(s);case'userRefs':owner_(s);return getUserReferenceData_();case'masters':owner_(s);return listMaster_(p.table);case'masterSave':owner_(s);return saveMaster_(p.table,p.item);case'masterDelete':owner_(s);return deleteMaster_(p.table,p.id);case'menuList':owner_(s);return listMaster_('MASTER_MENU');case'menuSave':owner_(s);return saveMaster_('MASTER_MENU',p.item);case'menuDelete':owner_(s);return deleteMaster_('MASTER_MENU',p.id);case'moduleList':return listMaster_('MASTER_MODUL');case'moduleSave':owner_(s);return saveMaster_('MASTER_MODUL',p.item);case'moduleDelete':owner_(s);return deleteMaster_('MASTER_MODUL',p.id);case'classSheets':classAccess_(s,p.classId);return classSheets_(p.classId);case'sheetHeaders':return sheetHeaders_(s,p.spreadsheetId,p.sheetName);case'createSheet':classAccess_(s,p.classId);return createSheet_(p.classId,p.sheetName,p.headers||[]);case'addColumns':return addColumns_(s,p.spreadsheetId,p.sheetName,p.headers||[]);case'deleteColumn':return deleteColumn_(s,p.spreadsheetId,p.sheetName,p.columnNumber);case'classConfig':classAccess_(s,p.classId);return classConfig_(p.classId);case'activateModule':classAccess_(s,p.classId);return activateModule_(s,p.classId,p.moduleId);case'userSave':return userSave_(s,p.item||{});case'userDelete':return userDelete_(s,p.id,p.classId);case'classAggregate':owner_(s);return aggregate_();case'readClassTable':classAccess_(s,p.classId);return readClassTable_(p.classId,p.sheetName);case'writeClassRow':classAccess_(s,p.classId);return writeClassRow_(p.classId,p.sheetName,p.row||{});case'deleteClassRow':classAccess_(s,p.classId);return deleteClassRow_(p.classId,p.sheetName,p.rowNumber);default:throw new Error('Action tidak dikenal: '+action);}}
function ensureMaster_(ss){Object.keys(MASTER).forEach(n=>{const sh=ss.getSheetByName(n)||ss.insertSheet(n);ensureHeaders_(sh,MASTER[n]);});}
function seedModules_(ss){const sh=ss.getSheetByName('MASTER_MODUL');if(sh.getLastRow()>1)return;SEED_MODULES.forEach(x=>append_(sh,MASTER.MASTER_MODUL,{id_modul:x[0],kode_modul:x[1],nama_kegiatan:x[2],description:x[3],sheet_name:x[4],headers_json:JSON.stringify(x[5]),roles:x[6].join(','),status:'ACTIVE',created_at:new Date(),updated_at:new Date()}));}
function ensureHeaders_(sh,h){const old=sh.getLastColumn()?sh.getRange(1,1,1,sh.getLastColumn()).getValues()[0]:[];h.forEach((x,i)=>{if(String(old[i]||'')!==x)sh.getRange(1,i+1).setValue(x);});if(sh.getLastColumn()>h.length)sh.deleteColumns(h.length+1,sh.getLastColumn()-h.length);sh.setFrozenRows(1);}
function master_(){const id=PropertiesService.getScriptProperties().getProperty(APP.masterProp);if(!id)throw new Error('MASTER Spreadsheet ID belum diatur.');return SpreadsheetApp.openById(id);}
function isBootstrapped_(){return PropertiesService.getScriptProperties().getProperty(APP.bootProp)==='1';}
function auth_(t){const x=t&&CacheService.getScriptCache().get('AUTH:'+t);if(!x)throw new Error('Sesi berakhir. Login kembali.');return JSON.parse(x);}
function owner_(s){if(s.role!=='owner')throw new Error('Hanya owner.');}
function classAccess_(s,id){if(s.role==='owner')return;const c=findClass_(id);if(!c)throw new Error('Kelas tidak ditemukan.');if(s.role==='admin_kelas'&&String(c.admin_username)===String(s.username))return;if(s.role==='siswa'&&String(c.id_kelas)===String(s.id_kelas))return;throw new Error('Akses kelas ditolak.');}
function findClass_(id){const r=read_(master_().getSheetByName('MASTER_KELAS')).rows.find(x=>String(x[0])===String(id));return r?obj_(MASTER.MASTER_KELAS,r):null;}
function listMaster_(table){if(table==='MASTER_USERS')ensureMasterUsersSchema_();const h=MASTER[table];if(!h)throw new Error('Master tidak tersedia.');return{headers:h,rows:read_(master_().getSheetByName(table)).rows.map(r=>obj_(h,r))};}
function ensureMasterUsersSchema_(){const sh=master_().getSheetByName('MASTER_USERS');if(!sh)return;const current=sh.getLastColumn()?sh.getRange(1,1,1,sh.getLastColumn()).getValues()[0].map(String):[],target=MASTER.MASTER_USERS;if(current.join('|')===target.join('|'))return;const oldRows=read_(sh).rows,oldIndex=Object.fromEntries(current.map((h,i)=>[h,i])),isLegacy=current.join('|')==='id_user|username|password_sha|nama|role|nip_nisn|id_kelas|status|created_at|updated_at',ref=getUserReferenceData_(),classes=ref.kelas,guru=ref.guru,karyawan=ref.karyawan;const rows=oldRows.map(r=>{if(!isLegacy)return target.map(h=>r[oldIndex[h]]===undefined?'':r[oldIndex[h]]);const role=norm_(r[4]),nip=String(r[5]||''),kelasId=String(r[6]||'');let idRef='',ssid='';if(role==='guru'){const g=guru.find(x=>norm_(x.nip)===norm_(nip));if(g)idRef=g.id_guru;}if(role==='karyawan'){const k=karyawan.find(x=>norm_(x.nip)===norm_(nip));if(k)idRef=k.id_karyawan;}if(role==='admin_kelas'){const k=karyawan.find(x=>norm_(x.nip)===norm_(nip));if(k)idRef=k.id_karyawan;const c=classes.find(x=>String(x.id_kelas)===kelasId);if(c)ssid=c.spreadsheet_id||'';}const person=guru.find(x=>String(x.id_guru)===idRef)||karyawan.find(x=>String(x.id_karyawan)===idRef)||{};return[r[0]||newId_('USER'),r[1]||'',r[2]||'',r[3]||'',role==='owner'?'':(person.email||''),role,idRef,nip,kelasId,ssid,r[7]||'ACTIVE',r[8]||new Date(),r[9]||new Date()];});sh.clearContents();sh.getRange(1,1,1,target.length).setValues([target]);if(rows.length)sh.getRange(2,1,rows.length,target.length).setValues(rows);sh.setFrozenRows(1);}
function saveMaster_(table,item){if(table==='MASTER_USERS')ensureMasterUsersSchema_();const h=MASTER[table];if(!h)throw new Error('Master tidak tersedia.');const sh=master_().getSheetByName(table),t=read_(sh),id=String(item.id||item.id_user||item.id_guru||item.id_karyawan||item.id_kelas||item.id_mapel||item.id_menu||item.id_modul||item.id_permission||'').trim();let i=t.rows.findIndex(r=>String(r[0])===id);const now=new Date(),o={};h.forEach(k=>o[k]=item[k]===undefined?'':item[k]);if(table==='MASTER_USERS')return saveMasterUser_(sh,item,id,i,t.rows);if(!id){o[h[0]]=newId_(table);o.created_at=now;}o.updated_at=now;if(i>=0)sh.getRange(i+2,1,1,h.length).setValues([h.map(k=>o[k])]);else append_(sh,h,o);return{o};}
function saveMasterUser_(sh,item,id,i,rows){const h=MASTER.MASTER_USERS,role=norm_(item.role);if(!ROLES.includes(role)||role==='siswa')throw new Error('MASTER_USERS hanya untuk owner, guru, karyawan, atau admin_kelas.');const username=norm_(item.username);if(!username)throw new Error('Username wajib diisi.');const duplicate=rows.findIndex((r,idx)=>idx!==i&&norm_(r[1])===username);if(duplicate>=0)throw new Error('Username sudah digunakan.');const o={};h.forEach(k=>o[k]=item[k]===undefined?'':item[k]);const current=i>=0?obj_(h,rows[i]):{},refs=getUserReferenceData_();o.id_user=id||newId_('USER');o.username=username;o.created_at=i>=0?current.created_at:new Date();o.updated_at=new Date();o.password_sha=item.password&&String(item.password).trim()?sha_(item.password):(current.password_sha||'');if(!o.password_sha)throw new Error('Password wajib untuk user baru.');if(role==='owner'){o.id_ref='OWNER';o.nama=String(item.nama||'Owner');o.email=String(item.email||'');o.nip_nisn='';o.id_kelas='';o.spreadsheet_id='';}else if(role==='guru'){const g=refs.guru.find(x=>String(x.id_guru)===String(item.id_ref)||norm_(x.nip)===norm_(item.nip_nisn));if(!g)throw new Error('Pilih guru dari MASTER_GURU.');o.id_ref=g.id_guru;o.nama=g.nama;o.email=g.email||'';o.nip_nisn=g.nip||'';o.id_kelas='';o.spreadsheet_id='';}else if(role==='karyawan'){const k=refs.karyawan.find(x=>String(x.id_karyawan)===String(item.id_ref)||norm_(x.nip)===norm_(item.nip_nisn));if(!k)throw new Error('Pilih karyawan dari MASTER_KARYAWAN.');o.id_ref=k.id_karyawan;o.nama=k.nama;o.email=k.email||'';o.nip_nisn=k.nip||'';o.id_kelas='';o.spreadsheet_id='';}else if(role==='admin_kelas'){const k=refs.karyawan.find(x=>String(x.id_karyawan)===String(item.id_ref));const c=refs.kelas.find(x=>String(x.id_kelas)===String(item.id_kelas));if(!k)throw new Error('Admin kelas harus dipilih dari MASTER_KARYAWAN.');if(!c)throw new Error('Kelas admin belum dipilih atau tidak valid.');if(!c.spreadsheet_id)throw new Error('Spreadsheet ID kelas belum diatur di MASTER_KELAS.');o.id_ref=k.id_karyawan;o.nama=k.nama;o.email=k.email||'';o.nip_nisn=k.nip||'';o.id_kelas=c.id_kelas;o.spreadsheet_id=c.spreadsheet_id;refs.kelas.forEach(cls=>{if(String(cls.admin_username)===username&&String(cls.id_kelas)!==String(c.id_kelas))throw new Error('Username admin kelas sudah terikat ke kelas lain.');});updateClassAdminUsername_(c.id_kelas,username);}o.role=role;o.status=String(item.status||current.status||'ACTIVE').toUpperCase();const values=h.map(k=>o[k]);if(i>=0)sh.getRange(i+2,1,1,h.length).setValues([values]);else sh.appendRow(values);return{o};}
function getUserReferenceData_(){const master=master_();return{guru:read_(master.getSheetByName('MASTER_GURU')).rows.map(r=>obj_(MASTER.MASTER_GURU,r)).filter(x=>norm_(x.status||'ACTIVE')!=='inactive'),karyawan:read_(master.getSheetByName('MASTER_KARYAWAN')).rows.map(r=>obj_(MASTER.MASTER_KARYAWAN,r)).filter(x=>norm_(x.status||'ACTIVE')!=='inactive'),kelas:read_(master.getSheetByName('MASTER_KELAS')).rows.map(r=>obj_(MASTER.MASTER_KELAS,r)).filter(x=>norm_(x.status||'ACTIVE')!=='inactive')};}
function updateClassAdminUsername_(classId,username){const sh=master_().getSheetByName('MASTER_KELAS'),rows=read_(sh).rows,idx=rows.findIndex(r=>String(r[0])===String(classId));if(idx<0)throw new Error('Kelas tidak ditemukan.');sh.getRange(idx+2,5).setValue(username);sh.getRange(idx+2,8).setValue(new Date());}
function deleteMaster_(table,id){const sh=master_().getSheetByName(table),r=read_(sh).rows,i=r.findIndex(x=>String(x[0])===String(id));if(i<0)throw new Error('Data tidak ditemukan.');sh.deleteRow(i+2);return{ok:true};}
function userSave_(s,item){if(s.role==='owner')return saveMaster_('MASTER_USERS',item);if(s.role!=='admin_kelas')throw new Error('Hanya owner/admin_kelas.');const cid=String(item.id_kelas||s.id_kelas||'');classAccess_(s,cid);const c=findClass_(cid),sh=students_(c),h=sh.getRange(1,1,1,9).getValues()[0].map(String),r=read_(sh).rows,id=String(item.id_siswa||item.id||''),i=id?r.findIndex(x=>String(x[0])===id):-1,o={id_siswa:id||newId_('SISWA'),username:norm_(item.username),password_sha:item.password?sha_(item.password):(i>=0?r[i][2]:''),nisn:String(item.nisn||''),nama:String(item.nama||''),kelas:c.nama_kelas,status:String(item.status||'ACTIVE'),created_at:i>=0?r[i][7]:new Date(),updated_at:new Date()};if(!o.username||!o.nama)throw new Error('Username dan nama wajib.');if(!o.password_sha)throw new Error('Password wajib untuk user baru.');if(i>=0)sh.getRange(i+2,1,1,9).setValues([h.map(k=>o[k])]);else sh.appendRow(h.map(k=>o[k]));return{o};}
function userDelete_(s,id,cid){if(s.role==='owner')return deleteMaster_('MASTER_USERS',id);classAccess_(s,cid);const sh=students_(findClass_(cid)),r=read_(sh).rows,i=r.findIndex(x=>String(x[0])===String(id));if(i<0)throw new Error('Siswa tidak ditemukan.');sh.deleteRow(i+2);return{ok:true};}
function students_(c){const ss=SpreadsheetApp.openById(c.spreadsheet_id),sh=ss.getSheetByName('SISWA')||ss.insertSheet('SISWA');ensureHeaders_(sh,['id_siswa','username','password_sha','nisn','nama','kelas','status','created_at','updated_at']);return sh;}
function classSheets_(id){const c=findClass_(id),ss=SpreadsheetApp.openById(c.spreadsheet_id);return{class:c,sheets:ss.getSheets().map(x=>({name:x.getName(),rows:x.getLastRow(),columns:x.getLastColumn()}))};}
function sheetHeaders_(s,ssid,name){const c=classBySpreadsheet_(ssid);if(c)classAccess_(s,c.id_kelas);else owner_(s);const sh=SpreadsheetApp.openById(ssid).getSheetByName(name);if(!sh)throw new Error('Sheet tidak ditemukan.');return{headers:sh.getRange(1,1,1,Math.max(1,sh.getLastColumn())).getValues()[0]};}
function createSheet_(cid,name,headers){const c=findClass_(cid),ss=SpreadsheetApp.openById(c.spreadsheet_id);if(!/^[A-Za-z0-9_ -]{1,90}$/.test(String(name)))throw new Error('Nama sheet tidak valid.');let sh=ss.getSheetByName(name);if(!sh)sh=ss.insertSheet(name);if(headers.length)addColumnsInternal_(sh,headers);sh.setFrozenRows(1);return{ok:true,sheet:name,headers:sh.getRange(1,1,1,Math.max(1,sh.getLastColumn())).getValues()[0]};}
function addColumns_(s,ssid,name,headers){const c=classBySpreadsheet_(ssid);if(c)classAccess_(s,c.id_kelas);else owner_(s);const sh=SpreadsheetApp.openById(ssid).getSheetByName(name);if(!sh)throw new Error('Sheet tidak ditemukan.');return{added:addColumnsInternal_(sh,headers)};}
function addColumnsInternal_(sh,headers){let cur=sh.getLastColumn()?sh.getRange(1,1,1,sh.getLastColumn()).getValues()[0].map(String):[],set=new Set(cur.map(normHead_)),added=[];headers.map(String).map(x=>x.trim()).filter(Boolean).forEach(x=>{const n=normHead_(x);if(!set.has(n)){sh.getRange(1,cur.length+1).setValue(x);cur.push(x);set.add(n);added.push(x);}});return added;}
function deleteColumn_(s,ssid,name,n){const c=classBySpreadsheet_(ssid);if(c)classAccess_(s,c.id_kelas);else owner_(s);const sh=SpreadsheetApp.openById(ssid).getSheetByName(name);if(!sh)throw new Error('Sheet tidak ditemukan.');n=Number(n);if(n<1||n>sh.getLastColumn())throw new Error('Kolom tidak valid.');sh.deleteColumn(n);return{ok:true};}
function classConfig_(id){const c=findClass_(id),ss=SpreadsheetApp.openById(c.spreadsheet_id),sh=ss.getSheetByName('SATRIA_CONFIG')||ss.insertSheet('SATRIA_CONFIG');if(sh.getLastRow()===0)sh.getRange('A1:B2').setValues([['key','value'],['active_modules','[]']]);sh.hideSheet();let active=[];try{active=JSON.parse(String(sh.getRange('B2').getValue()||'[]'));}catch(e){}return{class:c,activeModules:active,sheets:ss.getSheets().map(x=>x.getName())};}
function activateModule_(s,cid,mid){const c=findClass_(cid),ss=SpreadsheetApp.openById(c.spreadsheet_id),m=read_(master_().getSheetByName('MASTER_MODUL')).rows.find(r=>String(r[0])===String(mid));if(!m)throw new Error('Modul tidak ditemukan.');const mo=obj_(MASTER.MASTER_MODUL,m);if(!ss.getSheetByName(mo.sheet_name))throw new Error('Buat sheet '+mo.sheet_name+' terlebih dahulu.');const cfg=ss.getSheetByName('SATRIA_CONFIG')||ss.insertSheet('SATRIA_CONFIG');if(cfg.getLastRow()===0)cfg.getRange('A1:B2').setValues([['key','value'],['active_modules','[]']]);let a=[];try{a=JSON.parse(String(cfg.getRange('B2').getValue()||'[]'));}catch(e){}if(!a.includes(mid))a.push(mid);cfg.getRange('B2').setValue(JSON.stringify(a));cfg.hideSheet();return{ok:true,activeModules:a};}
function readClassTable_(cid,name){const c=findClass_(cid),sh=SpreadsheetApp.openById(c.spreadsheet_id).getSheetByName(name);if(!sh)throw new Error('Sheet tidak ditemukan.');const t=read_(sh);return{headers:t.headers,rows:t.rows.map(r=>obj_(t.headers,r))};}
function writeClassRow_(cid,name,row){const c=findClass_(cid),sh=SpreadsheetApp.openById(c.spreadsheet_id).getSheetByName(name);if(!sh)throw new Error('Sheet tidak ditemukan.');const h=read_(sh).headers;sh.appendRow(h.map(k=>row[k]===undefined?'':row[k]));return{ok:true};}
function deleteClassRow_(cid,name,n){const c=findClass_(cid),sh=SpreadsheetApp.openById(c.spreadsheet_id).getSheetByName(name);if(!sh)throw new Error('Sheet tidak ditemukan.');sh.deleteRow(Number(n));return{ok:true};}
function aggregate_(){return read_(master_().getSheetByName('MASTER_KELAS')).rows.map(r=>{const c=obj_(MASTER.MASTER_KELAS,r);try{const ss=SpreadsheetApp.openById(c.spreadsheet_id);return{id_kelas:c.id_kelas,nama_kelas:c.nama_kelas,spreadsheet_id:c.spreadsheet_id,sheets:ss.getSheets().map(x=>({name:x.getName(),rows:x.getLastRow(),columns:x.getLastColumn()}))};}catch(e){return{id_kelas:c.id_kelas,nama_kelas:c.nama_kelas,error:e.message};}});}
function classBySpreadsheet_(id){const r=read_(master_().getSheetByName('MASTER_KELAS')).rows.find(x=>String(x[3])===String(id));return r?obj_(MASTER.MASTER_KELAS,r):null;}
function dashboard_(s){if(s.role==='owner')return{role:s.role,classes:read_(master_().getSheetByName('MASTER_KELAS')).rows.length,users:read_(master_().getSheetByName('MASTER_USERS')).rows.length,modules:read_(master_().getSheetByName('MASTER_MODUL')).rows.length};const c=findClass_(s.id_kelas);return{role:s.role,className:c?c.nama_kelas:'',spreadsheetId:c?c.spreadsheet_id:''};}
function menus_(s){const sh=master_().getSheetByName('MASTER_MENU');if(!sh)return[];const menus=read_(sh).rows.map(r=>obj_(MASTER.MASTER_MENU,r)).filter(m=>String(m.status).toUpperCase()==='ACTIVE'&&String(m.roles||'').split(',').map(norm_).includes(norm_(s.role)));const ps=read_(master_().getSheetByName('MASTER_PERMISSION')).rows;return menus.map(m=>{const p=ps.find(x=>String(x[1])===String(s.role)&&String(x[2])===String(m.id_menu));return Object.assign(m,{can_view:p?String(p[3]).toUpperCase()!=='FALSE':true,can_add:p?String(p[4]).toUpperCase()==='TRUE':false,can_edit:p?String(p[5]).toUpperCase()==='TRUE':false,can_delete:p?String(p[6]).toUpperCase()==='TRUE':false});}).filter(m=>m.can_view).sort((a,b)=>Number(a.sort_order||0)-Number(b.sort_order||0));}
function read_(sh){const lc=sh.getLastColumn(),lr=sh.getLastRow();if(lc<1)return{headers:[],rows:[]};return{headers:sh.getRange(1,1,1,lc).getValues()[0].map(String),rows:lr>1?sh.getRange(2,1,lr-1,lc).getValues():[]};}
function obj_(h,r){const o={};h.forEach((k,i)=>o[k]=r[i] instanceof Date?r[i].toISOString():r[i]);return o;}
function append_(sh,h,o){sh.appendRow(h.map(k=>o[k]===undefined?'':o[k]));}
function sha_(x){return Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,String(x),Utilities.Charset.UTF_8).map(b=>(b<0?b+256:b).toString(16).padStart(2,'0')).join('');}
function norm_(x){return String(x||'').trim().toLowerCase();}
function normHead_(x){return norm_(x).replace(/[^a-z0-9]/g,'');}
function newId_(p){return String(p).replace(/[^A-Za-z0-9]/g,'')+'-'+Utilities.getUuid().slice(0,8).toUpperCase();}
