/** SATRIA BUILDER - modul belajar mandiri */
const MBELAJAR=Object.freeze({id:'MODUL-BELAJAR',name:'MODUL BELAJAR MANDIRI',sheet:'TRX_BELAJAR_MANDIRI',headers:['tanggal','siswa_id','nama_siswa','kelas','mata_pelajaran','materi','aktivitas','hasil_belajar','refleksi','bukti_fisik','created_at']});
function getMBelajarMandiri(token,action,p){const s=auth_(token);p=p||{};switch(action){case'get':return mbGet_(s,p);case'createSheet':return mbCreate_(s,p);case'activate':return mbActivate_(s,p);case'save':return mbSave_(s,p);case'delete':return mbDelete_(s,p);default:throw new Error('Action belajar mandiri tidak dikenal.');}}
function mbClasses_(s){if(s.role==='admin_kelas'||s.role==='siswa'){const c=findClass_(s.id_kelas);return c?[c]:[];}return read_(master_().getSheetByName('MASTER_KELAS')).rows.map(r=>obj_(MASTER.MASTER_KELAS,r)).filter(c=>norm_(c.status||'ACTIVE')!=='inactive'&&c.spreadsheet_id);}
function mbClass_(s,id){const a=mbClasses_(s),cid=String(id||s.id_kelas||a[0]?.id_kelas||''),c=a.find(x=>String(x.id_kelas)===cid);if(!c)throw new Error('Kelas belum dipilih.');classAccess_(s,c.id_kelas);if(!c.spreadsheet_id)throw new Error('Spreadsheet ID kelas belum diatur.');return c;}
function mbStudents_(c){const sh=SpreadsheetApp.openById(c.spreadsheet_id).getSheetByName('SISWA');if(!sh)return[];const t=read_(sh);return t.rows.map(r=>obj_(t.headers,r)).filter(x=>norm_(x.status||'ACTIVE')!=='inactive');}
function mbEnabled_(c){const sh=SpreadsheetApp.openById(c.spreadsheet_id).getSheetByName('SATRIA_CONFIG');if(!sh)return false;try{return JSON.parse(String(sh.getRange('B2').getValue()||'[]')).includes(MBELAJAR.id);}catch(e){return false;}}
function mbGet_(s,p){const c=mbClass_(s,p.classId),sh=SpreadsheetApp.openById(c.spreadsheet_id).getSheetByName(MBELAJAR.sheet),t=sh?read_(sh):null;return{class:c,classes:mbClasses_(s),students:mbStudents_(c),module:MBELAJAR,sheetExists:!!sh,enabled:s.role==='owner'||mbEnabled_(c),headers:t?t.headers:MBELAJAR.headers,rows:t?t.rows.map((r,i)=>{const o=obj_(t.headers,r);o.__row=i+2;return o;}):[],canCreateSheet:['owner','admin_kelas'].includes(s.role),canActivate:['owner','admin_kelas'].includes(s.role),canWrite:['owner','admin_kelas','guru','siswa'].includes(s.role)};}
function mbCreate_(s,p){if(!['owner','admin_kelas'].includes(s.role))throw new Error('Hanya owner/admin_kelas yang dapat membuat sheet.');const c=mbClass_(s,p.classId),ss=SpreadsheetApp.openById(c.spreadsheet_id),sh=ss.getSheetByName(MBELAJAR.sheet)||ss.insertSheet(MBELAJAR.sheet);ensureHeaders_(sh,MBELAJAR.headers);return{ok:true};}
function mbActivate_(s,p){if(!['owner','admin_kelas'].includes(s.role))throw new Error('Hanya owner/admin_kelas yang dapat mengaktifkan modul.');const c=mbClass_(s,p.classId),ss=SpreadsheetApp.openById(c.spreadsheet_id);if(!ss.getSheetByName(MBELAJAR.sheet))throw new Error('Buat sheet '+MBELAJAR.sheet+' terlebih dahulu.');const cfg=ss.getSheetByName('SATRIA_CONFIG')||ss.insertSheet('SATRIA_CONFIG');if(cfg.getLastRow()===0)cfg.getRange('A1:B2').setValues([['key','value'],['active_modules','[]']]);let a=[];try{a=JSON.parse(String(cfg.getRange('B2').getValue()||'[]'));}catch(e){}if(!a.includes(MBELAJAR.id))a.push(MBELAJAR.id);cfg.getRange('B2').setValue(JSON.stringify(a));cfg.hideSheet();return{ok:true};}
function mbSave_(s,p){const c=mbClass_(s,p.classId);if(!(s.role==='owner'||mbEnabled_(c)))throw new Error('Modul Belajar Mandiri belum aktif pada kelas ini.');const sh=SpreadsheetApp.openById(c.spreadsheet_id).getSheetByName(MBELAJAR.sheet);if(!sh)throw new Error('Sheet '+MBELAJAR.sheet+' belum dibuat.');const t=read_(sh),row=p.row||{},rn=Number(p.rowNumber||0);if(s.role==='siswa'){const me=mbStudents_(c).find(x=>String(x.id_siswa)===String(s.id_user));if(!me)throw new Error('Data siswa tidak ditemukan.');row.siswa_id=me.id_siswa;row.nama_siswa=me.nama;}row.kelas=c.nama_kelas;if(!row.tanggal)row.tanggal=new Date();if(!row.created_at)row.created_at=new Date();if(!row.siswa_id)throw new Error('Siswa wajib dipilih.');const vals=t.headers.map(h=>row[h]===undefined?'':row[h]);if(rn>=2&&rn<=sh.getLastRow()){const old=obj_(t.headers,sh.getRange(rn,1,1,t.headers.length).getValues()[0]);if(s.role==='siswa'&&String(old.siswa_id)!==String(s.id_user))throw new Error('Data siswa bukan milik Anda.');sh.getRange(rn,1,1,t.headers.length).setValues([vals]);}else sh.appendRow(vals);return{ok:true};}
function mbDelete_(s,p){const c=mbClass_(s,p.classId),sh=SpreadsheetApp.openById(c.spreadsheet_id).getSheetByName(MBELAJAR.sheet),rn=Number(p.rowNumber||0);if(!sh||rn<2||rn>sh.getLastRow())throw new Error('Baris tidak valid.');const h=read_(sh).headers,o=obj_(h,sh.getRange(rn,1,1,h.length).getValues()[0]);if(s.role==='siswa'&&String(o.siswa_id)!==String(s.id_user))throw new Error('Anda hanya dapat menghapus data sendiri.');if(!['owner','admin_kelas','guru','siswa'].includes(s.role))throw new Error('Akses ditolak.');sh.deleteRow(rn);return{ok:true};}
