/** SATRIA BUILDER - MODUL KEGIATAN LITERASI */
const MODLIT = Object.freeze({id:'MODUL-LITERASI',name:'MODUL KEGIATAN LITERASI',sheet:'TRX_LITERASI',headers:['tanggal','siswa_id','nama_siswa','kelas','jenis_literasi','judul_bacaan','ringkasan','refleksi','bukti_fisik','created_at']});
function modLitCall_(token,action,p){const s=auth_(token);return action==='get'?modLitGet_(s,p):action==='createSheet'?modLitCreateSheet_(s,p):action==='activate'?modLitActivate_(s,p):action==='save'?modLitSave_(s,p):action==='delete'?modLitDelete_(s,p):{error:'Action MODLIT tidak dikenal.'};}
function modLitClassList_(s){if(s.role==='admin_kelas'||s.role==='siswa'){const c=findClass_(s.id_kelas);return c?[c]:[];}return read_(master_().getSheetByName('MASTER_KELAS')).rows.map(r=>obj_(MASTER.MASTER_KELAS,r)).filter(c=>norm_(c.status||'ACTIVE')!=='inactive'&&c.spreadsheet_id);}
function modLitResolveClass_(s,id){const classes=modLitClassList_(s),cid=String(id||s.id_kelas||classes[0]?.id_kelas||'');const c=classes.find(x=>String(x.id_kelas)===cid);if(!c)throw new Error('Kelas belum dipilih.');if(!c.spreadsheet_id)throw new Error('Spreadsheet kelas belum diatur.');return c;}
function modLitActive_(c){const cfg=SpreadsheetApp.openById(c.spreadsheet_id).getSheetByName('SATRIA_CONFIG');if(!cfg)return false;try{return JSON.parse(String(cfg.getRange('B2').getValue()||'[]')).includes(MODLIT.id);}catch(e){return false;}}
function modLitStudents_(c){const sh=SpreadsheetApp.openById(c.spreadsheet_id).getSheetByName('SISWA');if(!sh)return[];const t=read_(sh);return t.rows.map(r=>obj_(t.headers,r)).filter(x=>norm_(x.status||'ACTIVE')!=='inactive');}
function modLitGet_(s,p){const c=modLitResolveClass_(s,p||{}),sh=SpreadsheetApp.openById(c.spreadsheet_id).getSheetByName(MODLIT.sheet),t=sh?read_(sh):null;return{ok:true,class:c,classes:modLitClassList_(s),module:MODLIT,enabled:s.role==='owner'||modLitActive_(c),canCreateSheet:['owner','admin_kelas'].includes(s.role),canActivate:['owner','admin_kelas'].includes(s.role),sheetExists:!!sh,headers:t?t.headers:MODLIT.headers,rows:t?t.rows.map((r,i)=>({...obj_(t.headers,r),__row:i+2})):[],students:modLitStudents_(c)};}
function modLitCreateSheet_(s,p){if(!['owner','admin_kelas'].includes(s.role))throw new Error('Hanya owner/admin_kelas yang dapat membuat sheet modul.');const c=modLitResolveClass_(s,p||{}),ss=SpreadsheetApp.openById(c.spreadsheet_id);let sh=ss.getSheetByName(MODLIT.sheet);if(!sh)sh=ss.insertSheet(MODLIT.sheet);ensureHeaders_(sh,MODLIT.headers);return{ok:true,sheet:MODLIT.sheet};}
function modLitActivate_(s,p){if(!['owner','admin_kelas'].includes(s.role))throw new Error('Hanya owner/admin_kelas yang dapat mengaktifkan modul.');const c=modLitResolveClass_(s,p||{}),ss=SpreadsheetApp.openById(c.spreadsheet_id);if(!ss.getSheetByName(MODLIT.sheet))throw new Error('Buat sheet '+MODLIT.sheet+' terlebih dahulu.');const cfg=ss.getSheetByName('SATRIA_CONFIG')||ss.insertSheet('SATRIA_CONFIG');if(cfg.getLastRow()===0)cfg.getRange('A1:B2').setValues([['key','value'],['active_modules','[]']]);let a=[];try{a=JSON.parse(String(cfg.getRange('B2').getValue()||'[]'));}catch(e){}if(!a.includes(MODLIT.id))a.push(MODLIT.id);cfg.getRange('B2').setValue(JSON.stringify(a));cfg.hideSheet();return{ok:true};}
function modLitSave_(s,p){const c=modLitResolveClass_(s,p||{});if(!(s.role==='owner'||modLitActive_(c)))throw new Error('Modul Kegiatan Literasi belum aktif pada kelas ini.');const sh=SpreadsheetApp.openById(c.spreadsheet_id).getSheetByName(MODLIT.sheet);if(!sh)throw new Error('Sheet '+MODLIT.sheet+' belum dibuat.');const t=read_(sh),row={...(p.row||{})},rn=Number(p.rowNumber||0),student=s.role==='siswa'?modLitStudents_(c).find(x=>String(x.id_siswa)===String(s.id_user)):null;if(s.role==='siswa'){if(!student)throw new Error('Data siswa tidak ditemukan.');row.siswa_id=student.id_siswa;row.nama_siswa=student.nama;}if('kelas'in row)row.kelas=c.nama_kelas;if('siswa_id'in row&&!row.siswa_id&&!student)throw new Error('Siswa wajib dipilih.');if('nama_siswa'in row&&!row.nama_siswa&&!student)throw new Error('Nama siswa wajib.');if('tanggal'in row&&!row.tanggal)row.tanggal=new Date();if('created_at'in row&&!row.created_at)row.created_at=new Date();const vals=t.headers.map(h=>row[h]===undefined?'':row[h]);if(rn>=2&&rn<=sh.getLastRow()){const old=obj_(t.headers,sh.getRange(rn,1,1,t.headers.length).getValues()[0]);if(s.role==='siswa'&&String(old.siswa_id)!==String(s.id_user))throw new Error('Akses data siswa ditolak.');sh.getRange(rn,1,1,t.headers.length).setValues([vals]);}else sh.appendRow(vals);return{ok:true};}
function modLitDelete_(s,p){const c=modLitResolveClass_(s,p||{}),sh=SpreadsheetApp.openById(c.spreadsheet_id).getSheetByName(MODLIT.sheet);if(!sh)throw new Error('Sheet tidak ditemukan.');const rn=Number(p.rowNumber||0);if(rn<2||rn>sh.getLastRow())throw new Error('Baris tidak valid.');if(s.role==='siswa'){const h=read_(sh).headers,o=obj_(h,sh.getRange(rn,1,1,h.length).getValues()[0]);if(String(o.siswa_id)!==String(s.id_user))throw new Error('Anda hanya dapat menghapus data sendiri.');}if(!['owner','admin_kelas','guru','siswa'].includes(s.role))throw new Error('Akses ditolak.');sh.deleteRow(rn);return{ok:true};}
function getModulKegiatanLiterasi(token,action,p){return modLitCall_(token,action,p||{});}
