/** SATRIA BUILDER - MODUL 7KAIH */
const MOD7 = Object.freeze({id:'MODUL-7KAIH',name:'MODUL 7KAIH',sheet:'TRX_7KAIH',headers:['tanggal','siswa_id','nama_siswa','kelas','indikator','uraian_kegiatan','catatan','bukti_fisik','created_at']});
function mod7Call_(token,action,p){const s=auth_(token);return action==='get'?mod7Get_(s,p):action==='createSheet'?mod7CreateSheet_(s,p):action==='activate'?mod7Activate_(s,p):action==='save'?mod7Save_(s,p):action==='delete'?mod7Delete_(s,p):{error:'Action MOD7 tidak dikenal.'};}
function mod7ClassList_(s){if(s.role==='admin_kelas'||s.role==='siswa'){const c=findClass_(s.id_kelas);return c?[c]:[];}return read_(master_().getSheetByName('MASTER_KELAS')).rows.map(r=>obj_(MASTER.MASTER_KELAS,r)).filter(c=>norm_(c.status||'ACTIVE')!=='inactive'&&c.spreadsheet_id);}
function mod7ResolveClass_(s,id){const classes=mod7ClassList_(s),cid=String(id||s.id_kelas||classes[0]?.id_kelas||'');const c=classes.find(x=>String(x.id_kelas)===cid);if(!c)throw new Error('Kelas belum dipilih.');if(!c.spreadsheet_id)throw new Error('Spreadsheet kelas belum diatur.');return c;}
function mod7Active_(c){if(c===null)return false;const ss=SpreadsheetApp.openById(c.spreadsheet_id),cfg=ss.getSheetByName('SATRIA_CONFIG');if(!cfg)return false;try{return JSON.parse(String(cfg.getRange('B2').getValue()||'[]')).includes(MOD7.id);}catch(e){return false;}}
function mod7Students_(c){const ss=SpreadsheetApp.openById(c.spreadsheet_id),sh=ss.getSheetByName('SISWA');if(!sh)return[];const t=read_(sh);return t.rows.map(r=>obj_(t.headers,r)).filter(x=>norm_(x.status||'ACTIVE')!=='inactive');}
function mod7Get_(s,p){const c=mod7ResolveClass_(s,p||{}),ss=SpreadsheetApp.openById(c.spreadsheet_id),sh=ss.getSheetByName(MOD7.sheet);return{ok:true,class:c,classes:mod7ClassList_(s),module:MOD7,enabled:s.role==='owner'||mod7Active_(c),canCreateSheet:['owner','admin_kelas'].includes(s.role),canActivate:['owner','admin_kelas'].includes(s.role),sheetExists:!!sh,headers:sh?read_(sh).headers:MOD7.headers,rows:sh?read_(sh).rows.map((r,i)=>{const o=obj_(read_(sh).headers,r);o.__row=i+2;return o;}):[],students:mod7Students_(c)};}
function mod7CreateSheet_(s,p){if(!['owner','admin_kelas'].includes(s.role))throw new Error('Hanya owner/admin_kelas yang dapat membuat sheet modul.');const c=mod7ResolveClass_(s,p||{}),ss=SpreadsheetApp.openById(c.spreadsheet_id);let sh=ss.getSheetByName(MOD7.sheet);if(!sh)sh=ss.insertSheet(MOD7.sheet);ensureHeaders_(sh,MOD7.headers);return{ok:true,sheet:MOD7.sheet};}
function mod7Activate_(s,p){if(!['owner','admin_kelas'].includes(s.role))throw new Error('Hanya owner/admin_kelas yang dapat mengaktifkan modul.');const c=mod7ResolveClass_(s,p||{}),ss=SpreadsheetApp.openById(c.spreadsheet_id);if(!ss.getSheetByName(MOD7.sheet))throw new Error('Buat sheet '+MOD7.sheet+' terlebih dahulu.');const cfg=ss.getSheetByName('SATRIA_CONFIG')||ss.insertSheet('SATRIA_CONFIG');if(cfg.getLastRow()===0)cfg.getRange('A1:B2').setValues([['key','value'],['active_modules','[]']]);let a=[];try{a=JSON.parse(String(cfg.getRange('B2').getValue()||'[]'));}catch(e){}if(!a.includes(MOD7.id))a.push(MOD7.id);cfg.getRange('B2').setValue(JSON.stringify(a));cfg.hideSheet();return{ok:true};}
function mod7Save_(s,p){const c=mod7ResolveClass_(s,p||{});if(!(s.role==='owner'||mod7Active_(c)))throw new Error('Modul 7KAIH belum aktif pada kelas ini.');const ss=SpreadsheetApp.openById(c.spreadsheet_id),sh=ss.getSheetByName(MOD7.sheet);if(!sh)throw new Error('Sheet '+MOD7.sheet+' belum dibuat.');const t=read_(sh),row={...(p.row||{})},rowNumber=Number(p.rowNumber||0),student=s.role==='siswa'?mod7Students_(c).find(x=>String(x.id_siswa)===String(s.id_user)):null;if(s.role==='siswa'){if(!student)throw new Error('Data siswa tidak ditemukan.');row.siswa_id=student.id_siswa;row.nama_siswa=student.nama;}if('kelas' in row)row.kelas=c.nama_kelas;if('siswa_id' in row&&!row.siswa_id&&!student)throw new Error('Siswa wajib dipilih.');if('nama_siswa' in row&&!row.nama_siswa&&!student)throw new Error('Nama siswa wajib.');if('tanggal' in row&&!row.tanggal)row.tanggal=new Date();if('created_at' in row&&(!row.created_at||rowNumber<2))row.created_at=new Date();const vals=t.headers.map(h=>row[h]===undefined?'':row[h]);if(rowNumber>=2&&rowNumber<=sh.getLastRow()){const old=obj_(t.headers,sh.getRange(rowNumber,1,1,t.headers.length).getValues()[0]);if(s.role==='siswa'&&String(old.siswa_id)!==String(s.id_user))throw new Error('Akses data siswa ditolak.');sh.getRange(rowNumber,1,1,t.headers.length).setValues([vals]);}else sh.appendRow(vals);return{ok:true};}
function mod7Delete_(s,p){const c=mod7ResolveClass_(s,p||{});const sh=SpreadsheetApp.openById(c.spreadsheet_id).getSheetByName(MOD7.sheet);if(!sh)throw new Error('Sheet tidak ditemukan.');const n=Number(p.rowNumber||0);if(n<2||n>sh.getLastRow())throw new Error('Baris tidak valid.');if(s.role==='siswa'){const headers=read_(sh).headers,r=sh.getRange(n,1,1,headers.length).getValues()[0],o=obj_(headers,r);if(String(o.siswa_id)!==String(s.id_user))throw new Error('Anda hanya dapat menghapus data sendiri.');}if(!['owner','admin_kelas','guru','siswa'].includes(s.role))throw new Error('Akses ditolak.');sh.deleteRow(n);return{ok:true};}
function getModul7Kaih(token,action,p){return mod7Call_(token,action,p||{});}
